/*
 * People info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserTime struct {
	Passport *Passport `json:"passport,omitempty"`

	TaskId int32 `json:"task_id,omitempty"`
}
