/*
 * People info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Passport struct {
	PassSerie int32 `json:"passSerie,omitempty"`

	PassNum int32 `json:"passNum,omitempty"`
}
