version: '3'

services:
  # App container
  app:
    build:
      context: ../
      dockerfile: build/app.Dockerfile
    image: golang_task-app:latest
    container_name: app
    environment:
      - DATABASE_LINK=host=database user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} port=5432 sslmode=disable
    networks:
      - app-network
    ports:
      - ${APP_PORT}:88
    depends_on:
      database:
        condition: service_healthy
  
  # PostgreSQL container
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data/:rw
    networks:
      - app-network
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready" ,"-h", "localhost"]
      interval: 1m
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge
volumes:
  db-data:
