version: '3'

services:
  # App container
  app:
    build:
      context: ../
      dockerfile: build/app.Dockerfile
    image: thunderlight-app:latest
    container_name: app
    environment:
      - DATABASE_LINK=${POSTGRES_USER}:${POSTGRES_PASSWORD}@tcp(database:5432)/${POSTGRES_DB}?charset=utf8&parseTime=True&loc=Local
    networks:
      - app-network
    ports:
      - 5174:88
    depends_on:
      database:
        condition: service_healthy
  
  # PostgreSQL container
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-data:/var/lib/postgresql/data/:rw
    networks:
      - app-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready" ,"-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge
volumes:
  db-data: